'use client';

import { useEffect, useState } from 'react';
import { Loader2, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function ThingsAIPage() {
  const [joke, setJoke] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchJoke = async () => {
    setLoading(true);
    setError(null);
    setJoke('');

    // Create AbortController for timeout (9 seconds for Hobby plan)
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 9000); // 9 seconds timeout

    try {
      const response = await fetch('/api/joke', {
        signal: controller.signal,
      });
      
      clearTimeout(timeoutId);
      
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to fetch joke');
      }

      setJoke(data.joke || 'No joke received');
    } catch (err) {
      clearTimeout(timeoutId);
      
      if (err instanceof Error && err.name === 'AbortError') {
        setError('Request timed out. Please try again.');
      } else {
        const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
        setError(errorMessage);
      }
      console.error('Error fetching joke:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchJoke();
  }, []);

  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="text-center space-y-8">
        <div>
          <h1 className="text-4xl font-bold mb-2">Things AI</h1>
          <p className="text-muted-foreground">
            Random jokes generated by Gemini AI
          </p>
        </div>

        <div className="bg-card border border-border rounded-lg p-8 min-h-[200px] flex items-center justify-center">
          {loading ? (
            <div className="flex flex-col items-center gap-4">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="text-muted-foreground">Generating a joke...</p>
            </div>
          ) : error ? (
            <div className="text-center space-y-4">
              <p className="text-destructive font-medium">{error}</p>
              {error.includes('quota') && (
                <p className="text-sm text-muted-foreground">
                  Your Gemini API quota has been exceeded. Please check your API key and billing settings.
                </p>
              )}
              {error.includes('timeout') && (
                <p className="text-sm text-muted-foreground">
                  The request is taking too long. This might be due to high API load. Please try again in a moment.
                </p>
              )}
            </div>
          ) : (
            <div className="space-y-4">
              <p className="text-lg leading-relaxed whitespace-pre-wrap">
                {joke}
              </p>
            </div>
          )}
        </div>

        <Button
          onClick={fetchJoke}
          disabled={loading}
          className="gap-2"
        >
          {loading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <RefreshCw className="h-4 w-4" />
              Get Another Joke
            </>
          )}
        </Button>

        <div className="text-xs text-muted-foreground mt-8">
          <p>Powered by Gemini 3 Flash Preview</p>
          <p className="mt-2">
            Reload the page or click the button above to generate a new joke
          </p>
        </div>
      </div>
    </div>
  );
}
